"""
A sales operations team wants to check the combined revenue contribution of two top salespeople. Find the total sales revenue generated by Samantha and Lisa.


Output the total sales revenue as a single number.

Table
sales_performance

"""
# Import your libraries
import pyspark
from pyspark.sql.functions import sum
onlythe2=sales_performance.filter((sales_performance["salesperson"]=="Samantha") | (sales_performance["salesperson"]=="Lisa"))

df=onlythe2.select(sum("sales_revenue"))

# To validate your solution, convert your final PySpark df to a pandas df
df.toPandas()